version: "8.2"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
     - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart:
      always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
     - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    restart:
      always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart:
      always

volumes:

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/srcs/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/srcs/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception