version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "1800:80"

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    ports:
      - "1900:80"